# Generated by Django 3.1 on 2024-02-06 01:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20240203_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 911376, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='about',
            name='publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 911411, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='build',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 908488, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='build',
            name='publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 908523, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='businesstonext',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 905113, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='careers',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 912783, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='careers',
            name='publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 912903, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='concept',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 905868, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='concept',
            name='publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 905902, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 916051, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 916085, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 910324, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 910359, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='design',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 907580, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='design',
            name='publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 907623, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 906707, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 906742, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 917875, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 917911, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='qualityassurance',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 909322, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='qualityassurance',
            name='publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 909357, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='services',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 914096, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='services',
            name='publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 914131, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicesdetail',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 914952, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicesdetail',
            name='publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 915020, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='termsnconditions',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 918860, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='termsnconditions',
            name='publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 1, 23, 11, 918901, tzinfo=utc)),
        ),
    ]
